services:
  # MongoDB Service
  mongodbIOT:
    image: mongo:latest
    container_name: mongodbIOT
    volumes:
      - mongodb_data_IOT:/data/db
    networks:
      - IOTWOW
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      TZ: "America/Mexico_City"
    ports:
      - "${PORT_MONGO}:${PORT_MONGO}"
    restart: unless-stopped

  # Microservices
  microservice_1:
    container_name: M1_MQTTDATASAVE
    build: ./IOTMS/M1
    ports:
      - "${PORT_MQTT_DATASAVE}:${PORT_MQTT_DATASAVE}"
    networks:
      - IOTWOW
    restart: unless-stopped
    env_file:
      - .env

  microservice_2:
    container_name: M2_DepuracionDB
    build: ./IOTMS/M2
    ports:
      - "${PORT_DEPURACIONDB}:${PORT_DEPURACIONDB}"
    networks:
      - IOTWOW
    restart: unless-stopped
    env_file:
      - .env

  microservice_3:
    container_name: M3_removedatosdup
    build: ./IOTMS/M3
    ports:
      - "${PORT_REMOVEDATOSDUP}:${PORT_REMOVEDATOSDUP}"
    networks:
      - IOTWOW
    restart: unless-stopped
    env_file:
      - .env

  microservice_4:
    container_name: M4_IOTWS
    build: ./IOTWS
    ports:
      - "${PORT_IOTWS}:${PORT_IOTWS}"
    networks:
      - IOTWOW
    restart: unless-stopped
    env_file:
      - .env

  microservice_5:
    container_name: M5_IOTAPIREST
    build: ./IOTAPIREST
    ports:
      - "${PORT_IOTAPIREST}:${PORT_IOTAPIREST}"
    networks:
      - IOTWOW
    restart: unless-stopped
    env_file:
      - .env

  # Portainer Service
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    networks:
      - IOTWOW

  # Grafana Service
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ROOT_USERNAME}
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - IOTWOW

volumes:
  mongodb_data_IOT:
  portainer_data:
  grafana_data:

networks:
  IOTWOW:
    driver: bridge
