version: '3.8'

services:
  mongodbIOT:
    image: mongo:latest
    container_name: mongodbIOT
    volumes:
      - mongodb_data_IOT:/data/db
    networks:
      - IOTWOW
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      TZ: "America/Mexico_City"  # Configuración de la zona horaria
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongodb_data_IOT:

networks:
  IOTWOW:
    driver: bridge
